#!/usr/bin/env bash
# vim: set ft=ruby:

# This file executes as a bash script, which turns around and executes Ruby via
# the line below. The -x argument to Ruby makes it discard everything before
# the second "!ruby" shebang. This allows us to work on Linux, where the
# shebang can only have one argument so we can't directly say
# "#!/usr/bin/env ruby --disable-gems". Thanks for that, Linux.
#
# If this seems confusing, don't worry. You can treat it as a normal Ruby file
# starting with the "!ruby" shebang below.

exec /usr/bin/env ruby --disable-gems -x "$0" $*
#!ruby

if RUBY_VERSION < '1.9.3'
  abort "error: Selecta requires Ruby 1.9.3 or higher."
end

require "optparse"
require "io/console"

KEY_CTRL_N = ?\C-n
KEY_CTRL_P = ?\C-p
KEY_CTRL_U = ?\C-u
KEY_CTRL_H = ?\C-h
KEY_CTRL_W = ?\C-w
KEY_CTRL_J = ?\C-j
KEY_CTRL_M = ?\C-m
KEY_DELETE = 127.chr # Equivalent to ?\C-?

class Selecta
  VERSION = [0, 0, 6]

  def main
    # We have to parse options before setting up the screen or trying to read
    # the input in case the user did '-h', an invalid option, etc. and we need
    # to terminate.
    options = Configuration.parse_options(ARGV)
    input_lines = $stdin.readlines

    search = Screen.with_screen do |screen, tty|
      config = Configuration.from_inputs(input_lines, options, screen.height)
      run_in_screen(config, screen, tty)
    end

    unless search.selection == Search::NoSelection
      puts search.selection
    end
  rescue Screen::NotATTY
    $stderr.puts(
      "Can't get a working TTY. Selecta requires an ANSI-compatible terminal.")
    exit(1)
  end

  def run_in_screen(config, screen, tty)
    search = Search.blank(config)

    # We emit the number of lines we'll use later so we don't clobber whatever
    # was already on the screen.
    config.visible_choices.times { tty.puts }
    begin
      search = ui_event_loop(search, screen, tty)
    ensure
      # Always move the cursor to the bottom so the next program doesn't draw
      # over whatever we left on the screen.
      screen.move_cursor(screen.height - 1, 0)
    end
    search
  end

  # Use the search and screen to process user actions until they quit.
  def ui_event_loop(search, screen, tty)
    while not search.done?
      Renderer.render!(search, screen)
      search = handle_key(search, tty.get_char)
    end
    search
  end

  # On each keystroke, generate a new search object
  def handle_key(search, key)
    case key

    when KEY_CTRL_N then search.down
    when KEY_CTRL_P then search.up

    when KEY_CTRL_U then search.clear_query
    when KEY_CTRL_W then search.delete_word
    when KEY_CTRL_H, KEY_DELETE then search.backspace

    when ?\r, KEY_CTRL_J, KEY_CTRL_M then search.done

    when /[[:print:]]/ then search.append_search_string(key.chr)

    else search
    end
  end
end

class Configuration < Struct.new(:visible_choices, :initial_search, :choices)
  def initialize(visible_choices, initialize, choices)
    # Constructor is defined to force argument presence; otherwise Struct
    # defaults missing arguments to nil
    super
  end

  def self.from_inputs(choices, options, screen_height=21)
    # Shrink the number of visible choices if the screen is too small
    visible_choices = [20, screen_height - 1].min

    choices = massage_choices(choices)
    Configuration.new(visible_choices, options.fetch(:search), choices)
  end

  def self.default_options
    parse_options([])
  end

  def self.parse_options(argv)
    options = {}

    parser = OptionParser.new do |opts|
      opts.banner = "Usage: #{$PROGRAM_NAME} [options]"

      opts.on_tail("-h", "--help", "Show this message") do |v|
        puts opts
        exit
      end

      opts.on_tail("--version", "Show version") do
        puts Selecta::VERSION.join('.')
        exit
      end

      options[:search] = ""
      opts.on("-s", "--search SEARCH", "Specify an initial search string") do |search|
        options[:search] = search
      end
    end

    begin
      parser.parse!(argv)
    rescue OptionParser::InvalidOption => e
      $stderr.puts e
      $stderr.puts parser
      exit 1
    end

    options
  end

  def self.massage_choices(choices)
    choices.map do |choice|
      # Encoding to UTF-8 with `:invalid => :replace` isn't good enough; it
      # still leaves some invalid characters. For example, this string will fail:
      #
      # echo "девуш\xD0:" | selecta
      #
      # Round-tripping through UTF-16, with `:invalid => :replace` as well,
      # fixes this. I don't understand why. I found it via:
      #
      # http://stackoverflow.com/questions/2982677/ruby-1-9-invalid-byte-sequence-in-utf-8
      if choice.valid_encoding?
        choice
      else
        utf16 = choice.encode('UTF-16', 'UTF-8', :invalid => :replace, :replace => '')
        utf16.encode('UTF-8', 'UTF-16')
      end.strip
    end
  end
end

class Search
  attr_reader :choices, :index, :query, :config, :match_state

  def initialize(vars)
    @config = vars.fetch(:config)
    @choices = vars.fetch(:choices)
    @index = vars.fetch(:index)
    @query = vars.fetch(:query)
    @done = vars.fetch(:done)
    @match_state = vars.fetch(:match_state)
    @vars = vars
  end

  def self.blank(config)
    new(:config => config,
        :choices => config.choices,
        :index => 0,
        :query => config.initial_search,
        :done => false,
        :match_state => MatchState.from_choices(config.choices)
       ).recompute_matches
  end

  # Construct a new Search by merging in a hash of changes.
  def merge(changes)
    vars = @vars.merge(changes)

    # If the query changed, throw away the old matches so that new ones will be
    # computed.
    matches_are_stale = vars.fetch(:query) != @query
    if matches_are_stale
      vars = vars.reject { |key| key == :matches }
    end

    Search.new(vars)
  end

  def done?
    @done
  end

  def selection
    if @aborted
      NoSelection
    else
      match = matches.fetch(@index) { NoSelection }
      if match == NoSelection
        match
      else
        match.original_choice
      end
    end
  end

  def down
    move_cursor(1)
  end

  def up
    move_cursor(-1)
  end

  def max_visible_choices
    [@config.visible_choices, matches.count].min
  end

  def append_search_string(string)
    merge(:index => 0,
          :query => @query + string)
    .recompute_matches
  end

  def backspace
    merge(:index => 0,
          :query => @query[0...-1])
    .recompute_matches
  end

  def clear_query
    merge(:index => 0,
          :query => "")
    .recompute_matches
  end

  def delete_word
    merge(:index => 0,
          :query => @query.sub(/[^ ]* *$/, ""))
    .recompute_matches
  end

  def done
    merge(:done => true)
  end

  def abort
    merge(:aborted => true)
  end

  def matches
    @match_state.for_query(@query)
  end

  def recompute_matches
    merge(:match_state => @match_state.update_for_query(@query))
  end

  private

  def move_cursor(direction)
    if max_visible_choices > 0
      index = (@index + direction) % max_visible_choices
      merge(:index => index)
    else
      self
    end
  end

  class NoSelection; end
end

class MatchState
  attr_reader :matches_by_query

  def initialize(matches_by_query)
    @matches_by_query = matches_by_query
  end

  def self.from_choices(choices)
    trivial_matches = choices.map { |choice| Match.trivial(choice) }
    MatchState.new({"" => trivial_matches})
  end

  def for_query(query)
    @matches_by_query.fetch(query)
  end

  def update_for_query(query)
    if @matches_by_query.has_key?(query)
      self
    else
      query = query.downcase

      matches = previous_matches(query).map do |match|
        choice = match.choice
        range = Score.score(choice, query)
        range ? match.refine(range) : nil
      end.compact.sort_by do |match|
        # Sort by score. In the case of a tie, favor shorter choice strings.
        [match.score, match.choice.length]
      end

      MatchState.new(@matches_by_query.merge(query => matches))
    end
  end

  private

  def previous_matches(query)
    if matches_by_query.has_key?(query)
      @matches_by_query.fetch(query)
    else
      previous_matches(query[0...-1])
    end
  end
end

class Match < Struct.new(:original_choice, :choice, :matching_range)
  def self.trivial(choice)
    empty_range = (0...0)
    new(choice, choice.downcase, empty_range)
  end

  def to_text
    if matching_range.none?
      Text[choice]
    else
      before = choice[0...matching_range.begin]
      matching = choice[matching_range.begin..matching_range.end]
      after = choice[(matching_range.end + 1)..-1]
      Text[before, :red, matching, :default, after]
    end
  end

  def score
    matching_range.count
  end

  def refine(new_range)
    Match.new(original_choice, choice, new_range)
  end
end

class Score
  class << self
    def score(choice, query)
      if choice.length > 0
        compute_match_range(choice, query.each_char.to_a)
      else
        nil
      end
    end

    # Find the length of the shortest substring matching the given characters.
    def compute_match_range(string, chars)
      first_char, *rest = chars

      best_count = Float::INFINITY
      best_range = nil

      each_index_of_char_in_string(string, first_char) do |first_index|
        last_index = find_end_of_match(string, rest, first_index)
        if last_index && (count = last_index - first_index) < best_count
          best_count = count
          best_range = (first_index..last_index)
        end
      end

      best_range
    end

    # Find all occurrences of the character in the string, returning their indexes.
    def each_index_of_char_in_string(string, char)
      index = 0
      while index
        index = string.index(char, index)
        if index
          yield index
          index += 1
        end
      end
    end

    # Find each of the characters in the string, moving strictly left to right.
    def find_end_of_match(string, chars, first_index)
      last_index = first_index
      chars.each do |this_char|
        index = string.index(this_char, last_index + 1)
        return nil unless index
        last_index = index
      end
      last_index
    end
  end
end

class Renderer < Struct.new(:search)
  def self.render!(search, screen)
    rendered = Renderer.new(search).render
    start_line = screen.height - search.config.visible_choices - 1
    screen.with_cursor_hidden do
      screen.write_lines(start_line, rendered.choices)
      screen.move_cursor(start_line, rendered.search_line.length)
    end
  end

  def render
    search_line = "#{match_count_label} > " + search.query

    matches = search.matches[0...search.config.visible_choices]
    matches = matches.each_with_index.map do |match, index|
      if index == search.index
        Text[:inverse] + match.to_text + Text[:reset]
      else
        match.to_text
      end
    end
    matches = correct_match_count(matches)
    lines = [search_line] + matches
    Rendered.new(lines, search_line)
  end

  def match_count_label
    choice_count = search.choices.length
    max_label_width = choice_count.to_s.length
    match_count = search.matches.count
    match_count.to_s.rjust(max_label_width)
  end

  def correct_match_count(matches)
    limited = matches[0, search.config.visible_choices]
    padded = limited + [""] * (search.config.visible_choices - limited.length)
    padded
  end

  class Rendered < Struct.new(:choices, :search_line)
  end

  private

  def replace_array_element(array, index, new_value)
    array = array.dup
    array[index] = new_value
    array
  end
end

class Screen
  def self.with_screen
    TTY.with_tty do |tty|
      screen = self.new(tty)
      screen.configure_tty
      begin
        raise NotATTY if screen.height == 0
        yield screen, tty
      ensure
        screen.restore_tty
        tty.puts
      end
    end
  end

  class NotATTY < RuntimeError; end

  attr_reader :tty

  def initialize(tty)
    @tty = tty
    @original_stty_state = tty.stty("-g")
  end

  def configure_tty
    # -echo: terminal doesn't echo typed characters back to the terminal
    # -icanon: terminal doesn't  interpret special characters (like backspace)
    tty.stty("-echo -icanon")
  end

  def restore_tty
    tty.stty("#{@original_stty_state}")
  end

  def suspend
    restore_tty
    begin
      yield
      configure_tty
    rescue
      restore_tty
    end
  end

  def with_cursor_hidden(&block)
    write_bytes(ANSI.hide_cursor)
    begin
      block.call
    ensure
      write_bytes(ANSI.show_cursor)
    end
  end

  def height
    size[0]
  end

  def width
    size[1]
  end

  def size
    height, width = tty.winsize
    [height, width]
  end

  def move_cursor(line, column)
    write_bytes(ANSI.setpos(line, column))
  end

  def write_line(line, text)
    write(line, 0, text)
  end

  def write_lines(line, texts)
    texts.each_with_index do |text, index|
      write(line + index, 0, text)
    end
  end

  def write(line, column, text)
    # Discard writes outside the main screen area
    write_unrestricted(line, column, text) if line < height
  end

  def write_unrestricted(line, column, text)
    text = Text[:default, text] unless text.is_a? Text
    write_text_object(line, column, text)
  end

  def write_text_object(line, column, text)
    # Blank the line before drawing to it
    write_bytes(ANSI.setpos(line, 0))
    write_bytes(" " * width)

    text.components.each do |component|
      if component.is_a? String
        write_bytes(ANSI.setpos(line, column))
        # Don't draw off the edge of the screen.
        #   - width - 1 is the last column we have (zero-indexed)
        #   - subtract the current column from that to get the number of
        #   columns we have left.
        chars_to_draw = [0, width - 1 - column].max
        component = expand_tabs(component)[0..chars_to_draw]
        write_bytes(component)
        column += component.length
      elsif component == :inverse
        write_bytes(ANSI.inverse)
      elsif component == :reset
        write_bytes(ANSI.reset)
      else
        if component =~ /_/
          fg, bg = component.to_s.split(/_/).map(&:to_sym)
        else
          fg, bg = component, :default
        end
        write_bytes(ANSI.color(fg, bg))
      end
    end
  end

  def expand_tabs(string)
    # Modified from http://markmail.org/message/avdjw34ahxi447qk
    tab_width = 8
    string.gsub(/([^\t\n]*)\t/) do
      $1 + " " * (tab_width - ($1.size % tab_width))
    end
  end

  def write_bytes(bytes)
    tty.console_file.write(bytes)
  end
end

class Text
  attr_reader :components

  def self.[](*args)
    new(args)
  end

  def initialize(components)
    @components = components
  end

  def ==(other)
    components == other.components
  end

  def +(other)
    Text[*(components + other.components)]
  end
end

class ANSI
  ESC = 27.chr

  class << self
    def escape(sequence)
      ESC + "[" + sequence
    end

    def clear
      escape "2J"
    end

    def hide_cursor
      escape "?25l"
    end

    def show_cursor
      escape "?25h"
    end

    def setpos(line, column)
      escape "#{line + 1};#{column + 1}H"
    end

    def color(fg, bg=:default)
      fg_codes = {
        :black => 30,
        :red => 31,
        :green => 32,
        :yellow => 33,
        :blue => 34,
        :magenta => 35,
        :cyan => 36,
        :white => 37,
        :default => 39,
      }
      bg_codes = {
        :black => 40,
        :red => 41,
        :green => 42,
        :yellow => 43,
        :blue => 44,
        :magenta => 45,
        :cyan => 46,
        :white => 47,
        :default => 49,
      }
      fg_code = fg_codes.fetch(fg)
      bg_code = bg_codes.fetch(bg)
      escape "#{fg_code};#{bg_code}m"
    end

    def inverse
      escape("7m")
    end

    def reset
      escape("0m")
    end
  end
end

class TTY < Struct.new(:console_file)
  def self.with_tty(&block)
    # Selecta reads data from stdin and writes it to stdout, so we can't draw
    # UI and receive keystrokes through them. Fortunately, all modern
    # Unix-likes provide /dev/tty, which IO.console gives us.
    console_file = IO.console
    tty = TTY.new(console_file)
    block.call(tty)
  end

  def get_char
    console_file.getc
  end

  def puts
    console_file.puts
  end

  def winsize
    console_file.winsize
  end

  def stty(args)
    command("stty #{args}")
  end

  private

  # Run a command with the TTY as stdin, capturing the output via a pipe
  def command(command)
    IO.pipe do |read_io, write_io|
      pid = Process.spawn(command, :in => "/dev/tty", :out => write_io)
      Process.wait(pid)
      raise "Command failed: #{command.inspect}" unless $?.success?
      write_io.close
      read_io.read
    end
  end
end

if $0 == __FILE__
  begin
    Selecta.new.main
  rescue Interrupt
    exit(1)
  end
end
